drop table if exists member CASCADE;
create table member
(
    member_id   bigint generated by default as identity,
    login_id    varchar(10),
    password    varchar(255),
    name    varchar(10),
    phonenumber varchar(11),
    email   varchar(50),
    grade   varchar(10),
    authority   varchar(15),
    agree_to_receive_sms    boolean,
    agree_to_receive_email  boolean,
    verify_email  boolean

    primary key (member_id)
);